POST  http://167.99.15.36:8001/api/pod-sessions/otp
Content-Type: application/json

{
    "otp": "GENG6E"
}
###

POST  http://167.99.15.36:8001/api/pods/slots
Content-Type: application/json
{
   "podId": "1", "date": "2025-06-09"
}